server:
  port: ${GATEWAY_SERVER_PORT:9191}

logging:
  level:
    org:
      springframework:
        security: DEBUG

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: http://localhost:6091/
          predicates:
          - Path=/login, /oauth2/authorization/discord, /accounts/**